# Generated by Django 3.2.19 on 2024-09-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_course_enrollment_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollmentaudit',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentaudit',
            name='org',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
